version: '3.9'

services:
  mining:
    image: fabian/ethminer
    build: .
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
    environment:
      - ADDRESS=PLACEHOLDER
      - WORKER=PLACEHOLDER
    devices:
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia1:/dev/nvidia1
      - /dev/nvidiactl:/dev/nvidiact
